#! /bin/bash
rm examples/*.jpeg
rm examples/*.png
rm examples/*.tiff
cargo run --release -- --debug --output-format jpeg -f examples/P9291284.ORF examples/PA071418.ORF examples/PA201627.ORF examples/PA201642.ORF
cargo run --release -- --debug --output-format jpeg --half-frame -f examples/P9261242.ORF examples/P9301342.ORF